name: deploy to lambda
#on: [push]
on:
  workflow_dispatch:

jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies within package directory
        run: |
          mkdir package
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target ./package
      - name: Zip the source code
        run: |
          cd package
          zip -r ../lambda_handler.zip .
          cd ..
          zip lambda_handler.zip lambda_function.py

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code --function-name crop-social-images --zip-file fileb://lambda_handler.zip --region us-west-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
